kind: Deployment
apiVersion: apps/v1
metadata:
  name: java
  namespace: peony
  selfLink: /apis/apps/v1/namespaces/peony/deployments/java
  uid: 3cfa3ede-dc8a-41ac-a184-4d1b456dc732
  resourceVersion: '11544374'
  generation: 2
  creationTimestamp: '2021-09-08T09:25:44Z'
  labels:
    dce.daocloud.io/app: java
  annotations:
    deployment.kubernetes.io/revision: '2'
    kubernetes.io/change-cause: update resources
spec:
  replicas: 1
  selector:
    matchLabels:
      dce.daocloud.io/component: java
  template:
    metadata:
      name: java
      creationTimestamp: null
      labels:
        dce.daocloud.io/app: java
        dce.daocloud.io/component: java
      annotations:
        dce.daocloud.io/parcel.egress.burst: '0'
        dce.daocloud.io/parcel.egress.rate: '0'
        dce.daocloud.io/parcel.ingress.burst: '0'
        dce.daocloud.io/parcel.ingress.rate: '0'
        dce.daocloud.io/parcel.net.type: calico
        dce.daocloud.io/parcel.net.value: default-ipv4-ippool
    spec:
      volumes:
        - name: configmap-96ce59f2
          configMap:
            name: java-config-test
            items:
              - key: application.yml
                path: application.yml
            defaultMode: 420
      containers:
        - name: java
          image: '10.20.24.3/daocloud/spring-boot-demo:0.0.3'
          resources:
            limits:
              cpu: '1'
              memory: '1073741824'
            requests:
              cpu: 256m
              memory: '1073741824'
          volumeMounts:
            - name: configmap-96ce59f2
              mountPath: /application.yml
              subPath: application.yml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: java-10.20.24.3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      schedulerName: default-scheduler
      dnsConfig:
        options:
          - name: single-request-reopen
            value: ''
          - name: ndots
            value: '2'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2021-09-08T09:25:51Z'
      lastTransitionTime: '2021-09-08T09:25:51Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2021-09-08T09:27:50Z'
      lastTransitionTime: '2021-09-08T09:25:44Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "java-cb876c4f6" has successfully progressed.

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: java-config-test
  namespace: peony
  selfLink: /api/v1/namespaces/peony/configmaps/java-config-test
  uid: a65e12fe-6a5d-4d9b-957d-b7f750d90bda
  resourceVersion: '11541970'
  creationTimestamp: '2021-09-08T09:22:03Z'
data:
  application.yml: |-
    yourName: 哈哈
    meName: 嘿嘿

---
kind: Service
apiVersion: v1
metadata:
  name: java-default
  namespace: peony
  selfLink: /api/v1/namespaces/peony/services/java-default
  uid: 22c1e1c3-7f37-40cc-9204-3acc0146b902
  resourceVersion: '11544774'
  creationTimestamp: '2021-09-08T09:25:45Z'
  labels:
    dce.daocloud.io/app: java
  annotations:
    io.daocloud.dce.serviceSelectorType: service
spec:
  ports:
    - name: java-default-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32065
  selector:
    dce.daocloud.io/component: java
  clusterIP: 172.31.49.172
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamily: IPv4
status:
  loadBalancer: {}
